# Generated by Django 6.0.5 on 2026-05-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='logs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporttHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_alerts', models.IntegerField()),
                ('uploaded_logs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.uploadedlogs')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.CharField(max_length=50)),
                ('falied_no_attempts', models.IntegerField()),
                ('first_seen_date', models.CharField(max_length=50)),
                ('first_seen_time', models.CharField(max_length=50)),
                ('uploaded_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.uploadedlogs')),
            ],
        ),
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_logs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.uploadedlogs')),
            ],
        ),
    ]
