# Generated by Django 6.0.5 on 2026-05-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerts',
            old_name='uploaded_logs',
            new_name='uploaded_log',
        ),
    ]
