# Generated by Django 6.0.5 on 2026-05-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_rename_uploaded_logs_alerts_uploaded_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedip',
            old_name='falied_no_attempts',
            new_name='failed_no_attempts',
        ),
        migrations.RenameField(
            model_name='reportthistory',
            old_name='uploaded_logs',
            new_name='uploaded_log',
        ),
    ]
