# Generated by Django 6.0.5 on 2026-05-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_rename_falied_no_attempts_detectedip_failed_no_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedlogs',
            name='file_hash',
            field=models.CharField(default='temp', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
