# Generated by Django 6.0.5 on 2026-05-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_uploadedlogs_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedlogs',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
